name: docker-light-images - test  # soup-msa-service CICD
on:
  push:
    branches:
      - test/docker-light-image-no-log

env:
  ADMIN_REPOSITORY: soup-admin-service-no-log
  MEMBER_REPOSITORY: soup-member-service-no-log
  SEARCH_REPOSITORY: soup-search-service-no-log
jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        id: login-dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: BUILD soup-msa-service images and push image to dockerhub
        id: soup-msa-service_build
        env:
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          ADMIN_REPOSITORY: ${{ env.ADMIN_REPOSITORY }}
          MEMBER_REPOSITORY: ${{ env.MEMBER_REPOSITORY }}
          SEARCH_REPOSITORY: ${{ env.SEARCH_REPOSITORY }}
        run: |
          ./gradlew clean
          ./gradlew build 
          IMAGE_TAG=$(date +%s)
          echo "new tag: ${IMAGE_TAG}"
          ./gradlew :soup-admin-service:bootBuildImage --imageName $REGISTRY/$ADMIN_REPOSITORY:$IMAGE_TAG
          ./gradlew :soup-member-service:bootBuildImage --imageName $REGISTRY/$MEMBER_REPOSITORY:$IMAGE_TAG
          ./gradlew :soup-search-service:bootBuildImage --imageName $REGISTRY/$SEARCH_REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$ADMIN_REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$MEMBER_REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$SEARCH_REPOSITORY:$IMAGE_TAG
          docker tag $REGISTRY/$ADMIN_REPOSITORY:$IMAGE_TAG $REGISTRY/$ADMIN_REPOSITORY:latest
          docker tag $REGISTRY/$MEMBER_REPOSITORY:$IMAGE_TAG $REGISTRY/$MEMBER_REPOSITORY:latest
          docker tag $REGISTRY/$SEARCH_REPOSITORY:$IMAGE_TAG $REGISTRY/$SEARCH_REPOSITORY:latest
          docker push $REGISTRY/$ADMIN_REPOSITORY:latest
          docker push $REGISTRY/$MEMBER_REPOSITORY:latest
          docker push $REGISTRY/$SEARCH_REPOSITORY:latest

